//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5_Mypham.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_MyPham_CocoonEntities : DbContext
    {
        public QL_MyPham_CocoonEntities()
            : base("name=QL_MyPham_CocoonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NHATKY_GIA> NHATKY_GIA { get; set; }
        public virtual DbSet<PHUONGTHUCTHANHTOAN> PHUONGTHUCTHANHTOANs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<TONKHO> TONKHOes { get; set; }
    
        public virtual int sp_GopHoaDon(string maKH, Nullable<System.DateTime> ngay)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GopHoaDon", maKHParameter, ngayParameter);
        }
    
        public virtual int sp_HoanTraHang(string maHD)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HoanTraHang", maHDParameter);
        }
    
        public virtual int sp_HuyHoaDon(string maHD)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HuyHoaDon", maHDParameter);
        }
    
        public virtual int sp_NhapKho(string maSP, Nullable<int> soLuongNhap)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var soLuongNhapParameter = soLuongNhap.HasValue ?
                new ObjectParameter("SoLuongNhap", soLuongNhap) :
                new ObjectParameter("SoLuongNhap", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NhapKho", maSPParameter, soLuongNhapParameter);
        }
    
        public virtual int sp_OnboardKH(string maKH, string diaChiMoi, string maNV)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var diaChiMoiParameter = diaChiMoi != null ?
                new ObjectParameter("DiaChiMoi", diaChiMoi) :
                new ObjectParameter("DiaChiMoi", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_OnboardKH", maKHParameter, diaChiMoiParameter, maNVParameter);
        }
    
        public virtual ObjectResult<sp_SanPhamSapHetHang_Result> sp_SanPhamSapHetHang(Nullable<int> nguong)
        {
            var nguongParameter = nguong.HasValue ?
                new ObjectParameter("Nguong", nguong) :
                new ObjectParameter("Nguong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SanPhamSapHetHang_Result>("sp_SanPhamSapHetHang", nguongParameter);
        }
    
        public virtual int sp_TaoHoaDon(string maHD, string maNV, string maKH)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoHoaDon", maHDParameter, maNVParameter, maKHParameter);
        }
    
        public virtual int sp_TaoKhuyenMai(string maKM, string ten, Nullable<double> tiLeGiam, Nullable<System.DateTime> ngayBD, Nullable<System.DateTime> ngayKT)
        {
            var maKMParameter = maKM != null ?
                new ObjectParameter("MaKM", maKM) :
                new ObjectParameter("MaKM", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var tiLeGiamParameter = tiLeGiam.HasValue ?
                new ObjectParameter("TiLeGiam", tiLeGiam) :
                new ObjectParameter("TiLeGiam", typeof(double));
    
            var ngayBDParameter = ngayBD.HasValue ?
                new ObjectParameter("NgayBD", ngayBD) :
                new ObjectParameter("NgayBD", typeof(System.DateTime));
    
            var ngayKTParameter = ngayKT.HasValue ?
                new ObjectParameter("NgayKT", ngayKT) :
                new ObjectParameter("NgayKT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoKhuyenMai", maKMParameter, tenParameter, tiLeGiamParameter, ngayBDParameter, ngayKTParameter);
        }
    
        public virtual ObjectResult<sp_TimKiemSP_Result> sp_TimKiemSP(string ten, string maLoai, Nullable<decimal> giaMin, Nullable<decimal> giaMax)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var giaMinParameter = giaMin.HasValue ?
                new ObjectParameter("GiaMin", giaMin) :
                new ObjectParameter("GiaMin", typeof(decimal));
    
            var giaMaxParameter = giaMax.HasValue ?
                new ObjectParameter("GiaMax", giaMax) :
                new ObjectParameter("GiaMax", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiemSP_Result>("sp_TimKiemSP", tenParameter, maLoaiParameter, giaMinParameter, giaMaxParameter);
        }
    
        public virtual ObjectResult<sp_TopBanChay_Result> sp_TopBanChay(Nullable<System.DateTime> tu, Nullable<System.DateTime> den, Nullable<int> topN)
        {
            var tuParameter = tu.HasValue ?
                new ObjectParameter("Tu", tu) :
                new ObjectParameter("Tu", typeof(System.DateTime));
    
            var denParameter = den.HasValue ?
                new ObjectParameter("Den", den) :
                new ObjectParameter("Den", typeof(System.DateTime));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("TopN", topN) :
                new ObjectParameter("TopN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TopBanChay_Result>("sp_TopBanChay", tuParameter, denParameter, topNParameter);
        }
    
        public virtual int sp_TraHangTungPhan(string maHD, string maSP, Nullable<int> sLTra)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var sLTraParameter = sLTra.HasValue ?
                new ObjectParameter("SLTra", sLTra) :
                new ObjectParameter("SLTra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TraHangTungPhan", maHDParameter, maSPParameter, sLTraParameter);
        }
    }
}
