//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5_Mypham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public System.DateTime NgaySX { get; set; }
        public System.DateTime HanSD { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MaLoai { get; set; }
        public string MaNCC { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<decimal> GiaVon { get; set; }
        public string LoaiDa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual TONKHO TONKHO { get; set; }
    }
}
