//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom5_Mypham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONKHO
    {
        public string MaSP { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
